server.port: 8443

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/demo?serverTimezone=UTC
    username: root
    password: pass

  jpa:
    hibernate:
        ddl-auto: update

---

spring:
  profiles: live
  datasource:
    url: jdbc:mysql://database/demo?serverTimezone=UTC
